export const Config = {
  port: Number(process.env.PORT) || 3333,
}

export const ErrorMessages = {
  invalidLeadId: 'ID do lead inválido',
  leadNotFound: 'Lead não encontrado',
  invalidUsuarioId: 'ID do usuário responsável inválido',
  usuarioNotFound: 'Usuário responsável não encontrado',
  nomeRequired: 'Nome é obrigatório',
  dataCadastroRequired: 'Data de cadastro é obrigatória',
  invalidDataCadastro: 'Data de cadastro inválida',
  emailRequired: 'Email é obrigatório',
  senhaRequired: 'Senha é obrigatória',
  invalidCredentials: 'Email ou senha inválidos',
  leadHasOportunidades: 'Lead possui oportunidades vinculadas',
  invalidOportunidadeId: 'ID da oportunidade inválido',
  oportunidadeNotFound: 'Oportunidade não encontrada',
  tituloRequired: 'Título é obrigatório',
  invalidLeadIdRef: 'Lead vinculado inválido',
  leadRefNotFound: 'Lead vinculado não encontrado',
  invalidEtapaFunilId: 'Etapa do funil inválida',
  etapaFunilNotFound: 'Etapa do funil não encontrada',
  invalidValorEstimado: 'Valor estimado inválido',
  invalidPrioridade: 'Prioridade inválida',
  invalidUsuarioIdParam: 'ID do usuário inválido',
  usuarioNotFound: 'Usuário não encontrado',
  usuarioNomeRequired: 'Nome é obrigatório',
  usuarioCargoRequired: 'Cargo é obrigatório',
  usuarioEmailRequired: 'Email é obrigatório',
  usuarioEmailInUse: 'Email já cadastrado',
  usuarioSenhaRequired: 'Senha é obrigatória',
  usuarioHasLeads: 'Usuário possui leads vinculados',
  usuarioHasOportunidades: 'Usuário possui oportunidades vinculadas',
  invalidPerfilAcesso: 'Perfil de acesso inválido',
  relatorioDataInicioRequired: 'Data inicial é obrigatória',
  relatorioDataFimRequired: 'Data final é obrigatória',
  relatorioDatasInvalidas: 'Datas do relatório inválidas',
  relatorioPeriodoInvalido: 'Data inicial não pode ser maior que a data final',
  importFileRequired: 'Arquivo da planilha é obrigatório',
  importFileInvalid: 'Formato inválido. Use .xlsx, .xls ou .csv',
  importSheetEmpty: 'Planilha vazia ou sem cabeçalho',
  importColumnNomeRequired: 'Coluna "nome" é obrigatória na planilha',
  importRuleInvalid: 'Regra de importação inválida',
  invalidInteracaoId: 'ID da interação inválido',
  interacaoNotFound: 'Interação não encontrada',
  interacaoTipoRequired: 'Tipo da interação é obrigatório',
  interacaoTipoInvalid: 'Tipo da interação inválido',
  interacaoDescricaoRequired: 'Descrição é obrigatória',
  interacaoDataRequired: 'Data da interação é obrigatória',
  interacaoDataInvalid: 'Data da interação inválida',
  interacaoOportunidadeInvalid: 'Oportunidade vinculada inválida',
  interacaoOportunidadeNotFound: 'Oportunidade vinculada não encontrada',
  interacaoOportunidadeLeadMismatch: 'Oportunidade não pertence a este lead',
  invalidMotivoPerdaId: 'ID do motivo de perda inválido',
  motivoPerdaNotFound: 'Motivo de perda não encontrado',
  motivoPerdaNomeRequired: 'Nome do motivo é obrigatório',
  motivoPerdaNomeInUse: 'Motivo de perda já cadastrado',
  motivoPerdaInUse: 'Motivo vinculado a oportunidades e não pode ser excluído',
  motivoPerdaRequired: 'Motivo de perda é obrigatório',
  oportunidadeJaPerdida: 'Oportunidade já está marcada como perdida',
  etapaPerdidaNotFound: 'Etapa "Perdida" não configurada no funil',
  invalidTarefaId: 'ID da tarefa inválido',
  tarefaNotFound: 'Tarefa não encontrada',
  tarefaTituloRequired: 'Título da tarefa é obrigatório',
  tarefaDataPrazoRequired: 'Data de prazo é obrigatória',
  tarefaDataPrazoInvalid: 'Data de prazo inválida',
  tarefaStatusInvalid: 'Status da tarefa inválido',
  tarefaOportunidadeInvalid: 'Oportunidade vinculada inválida',
  tarefaOportunidadeNotFound: 'Oportunidade vinculada não encontrada',
  tarefaOportunidadeLeadMismatch: 'Oportunidade não pertence a este lead',
  invalidPropostaId: 'ID da proposta inválido',
  propostaNotFound: 'Proposta não encontrada',
  propostaTituloRequired: 'Título da proposta é obrigatório',
  propostaValorInvalid: 'Valor da proposta inválido',
  propostaStatusInvalid: 'Status da proposta inválido',
  propostaDataRequired: 'Data da proposta é obrigatória',
  propostaDataInvalid: 'Data da proposta inválida',
}
